kind = "web"
previewPath = "/"
title = "HK Projects"
version = "1.0.0"
id = "artifacts/HK-Projects"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24148

[services.development]
run = "pnpm --filter @workspace/HK-Projects run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/HK-Projects", "run", "build" ]
publicDir = "artifacts/HK-Projects/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24148"
BASE_PATH = "/"
